language: python

python:
- 3.6
# Python 2.7 caused test failures
env:
  matrix:
    - PANDAS_VERSION='0.23.3'  # Latest: If this changes update deploy.
    - PANDAS_VERSION='0.22.0'  # Last 0.22: Dec 31, 2017
    - PANDAS_VERSION='0.21.1'  # Last 0.21: Dec 13, 2017
    # Earlier versions of pandas caused test failures.
matrix:
  fast_finish: true

install:
- set -o errexit
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
- pip install pandas==$PANDAS_VERSION

script: ./test.sh
deploy:
  # Defaults to only deploy on master;
  # PyPi blocks the same version from being uploaded twice.
  provider: pypi
  distributions: sdist bdist_wheel
  user: scottx611x
  password:
    secure: "KMp2DvkaOotCPlWjGNj4iVkutmIWFabjsrqvW2dSKZdu5mN8G6Ag2kHb6YMLLeW/Wq0O9FF6pltpqnhBcV8ejXKgwKaPXtwD2OIRwiyg+xcqjO1giysf4Teetw/tA8zMuHfTorBl3s6ZFdFQQ4UBs3SH6V1fJ4D/0Paz8RhiTkJCSfKjaRXZpObFphMy0BwXJO/A0XICIT1MEVXXAIwMDo3wu9Fctd5JyKD6QxY+EjhCPOfX4MIPy3pYmbkiNLO/ONzGUSitGt0G/NOiSr/zOm+PFBXD/aj/kh7Yq7MWJWzMOzfJolZYwla6Xdj8WW/a9lGBRBC2seoU5gDTQBr3bDthNhnWFsU4mtkswv1nfJLt8jPvK8c8e/Irm6nZ3iC6yyyYWurO6xJFqp2i/Jk0EFDR0BZvo9iJaQXuyL8Atb88Eomea+OYPZ8kgRpI2+gbUbJwr4J/NcY09YAPZIGPyp3OzXmZRuZxivCDYnvBoSH847O6BljiNOSGXHpW5OdOOvlu6YGmwMd43Qcwolux7jUf/Gu7E+NKi7Vd7s7K/9NFIscIFZXaGRwfDzBkkT5eHT6toc8iqw/9Kr84g40ZKfXRY74B9mCiZfRVoBWJIHnhhsKjVJ8JDiQ3+xgVHBvccJ1wFXmdxM1boqP2nAtSgrwaG5M9YRDD7ja7PTStkxU=" 
  on:
    branch: master
    python: 3.6
    condition: $PANDAS_VERSION = '0.23.3'
